### ISSUE TITLE
On Enabling error

### ISSUE THREAD

**Issue by DinoNuggets2** [MarcosVLl2/GhostSpectatorReworked#1]
This error occours as the server is restarting/starting:

`[ERROR] [Exiled.Loader] Plugin "GhostSpectatorReworked" threw an exception while enabling: System.TypeLoadException: Could not resolve type with token 01000034 (from typeref, class/assembly Exiled.Events.EventArgs.EnteringEnvironmentalHazardEventArgs, Exiled.Events, Version=5.3.0.0, Culture=neutral, PublicKeyToken=null)`

**Comment by xNexusACS** [comment]
@DinoNuggets2 you need Exiled 5.3 for the plugin, bcs as the error says, your Exiled.Events assembly don't have the EnteringEnviromentalHazardEventArgs
